cantaloupe-project/cantaloupe

build/assembly.xml
pom.xml

The [project.version variable](https://maven.apache.org/guides/introduction/introduction-to-the-pom.html#Project_Interpolation_and_Variables) can be used to retrieve the current version in pom.xml.
With that, it won't be necessary to keep both cantaloupe.version and the pom.xml version in sync, preventing issues, and simplifying the build pipeline.
Tested locally, get the Cantaloupe-3.3-SNAPSHOT.zip in my target folder, just as before the change.
Bruno

Use project.version variable for assembly

---

website/manual/3.3/deployment.html

The link to the section reverse proxying with Nginx is broken in the table of contents.

Fix link to deployment section with Nginx

---

src/main/java/edu/illinois/library/cantaloupe/StandaloneEntry.java

The first time I started the application in my Eclipse workspace I got a NPE, and didn't understand if I was doing some mistake, or if there was a bug in the develop branch.
The output also didn't include the usage, but after reading the code I noticed that I had to provide a configuration file (I should have read the manual actually, I know :-) ).
This pull request adds a usage method, and checks if the configuration object was not created, and if so, prints the usage and exists.
It also prints the usage for the other cases like when there is no file, or instead of a file the user provided a directory.

Add usage method, and print the usage when no config was provided, instead of throwing NullPointerException

---

pom.xml

The javax.servlet-api jar was scoped to compile, and because of this I couldn't run Cantaloupe in Eclipse. When trying to run with `mvn clean tomcat:run` I got:
```
Jul 25, 2017 12:52:48 PM org.apache.catalina.core.StandardContext loadOnStartup
SEVERE: Servlet /Cantaloupe threw load() exception
java.lang.ClassCastException: edu.illinois.library.cantaloupe.EntryServlet cannot be cast to javax.servlet.Servlet
at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1116)
at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:993)
at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4350)
```
Marking it as provided, everything works in Eclipse. Running `mvn clean package -DskipTests`, I get the `.war` and `.zip` files.
Comparing …

Make javax.servlet-api provided

---

src/main/java/edu/illinois/library/cantaloupe/ApplicationInitializer.java
src/main/java/edu/illinois/library/cantaloupe/EntryServlet.java
src/main/java/edu/illinois/library/cantaloupe/StandaloneEntry.java
src/main/java/edu/illinois/library/cantaloupe/config/ConfigurationFactory.java
src/main/webapp/WEB-INF/web.xml
src/test/java/edu/illinois/library/cantaloupe/StandaloneEntryTest.java

Hi,
This commit introduces a new `ServletContextListener`, `ApplicationInitializer`, which offloads parts of the responsibilities from `EntryServlet`. The `EntryServlet` was both serving as Jersey entry point servlet, but also as handling application initialization.
This is now done in the listener. The `ConfigurationFactory` is also throwing an exception when there is no configuration file, instead of printing to `stderr` and later throwing a `NullPointerException`.
With these changes, it is easy to identify when the application fails to initialize. Which is useful when a WAR application is deployed to a platform like AWS Elastic Beanstalk.

Use ServletContextInitializer for application initialization

---

README.md
pom.xml
src/main/java/edu/illinois/library/cantaloupe/operation/overlay/StringOverlay.java
src/test/java/edu/illinois/library/cantaloupe/operation/overlay/BasicStringOverlayServiceTest.java
src/test/java/edu/illinois/library/cantaloupe/operation/overlay/DelegateOverlayServiceTest.java
src/test/java/edu/illinois/library/cantaloupe/operation/overlay/StringOverlayTest.java

Right now I have one test failing. This PR includes a `nodeps` profile as discussed in #130, for running the unit tests that do not require external accounts in AWS/Azure/etc, nor certain dependencies such as Kakadu or Selenium.
There are also several tests that use font family, and not family name. The problem with that is that the value changes quite a bit in Linux/Windows. So this PR also addresses this problem, by using the font name.
The Helvetica font is not installed in Ubuntu, or at least is not easily installed. Tried the `ms-mscorefonts-installer` but didn't get the Helvetica font, so changed by Arial.

Use a test profile, and fix some tests

---

pom.xml
src/main/java/edu/illinois/library/cantaloupe/cache/AmazonS3Cache.java
src/main/java/edu/illinois/library/cantaloupe/cache/AzureStorageCache.java

This PR introduces the [Maven Enforcer Plugin](http://maven.apache.org/enforcer/maven-enforcer-plugin/) to the `verify` phase of the project build lifecycle.
And it utilises a plug-in that makes sure we do not use transitive dependencies. It means that if we have dependencies like `commons-collections` (which includes `commons-lang` version 2.x) and `commons-lang3`, in case we use `StringUtils` from `commons-lang` 2.x, the build will fail. As `commons-lang` 2.x is a transitive dependency.
When running `mvn verify -DskipTests=true`, I initially got the following errors:
```
[WARNING] Rule 0: de.is24.maven.enforcer.rules.IllegalTransitiveDependencyCheck failed with message:
Found 53 illegal transitive type dependencies in artifact 'edu.illinois.library.cantaloupe:Cantaloupe:war:3.4-SNAPSHOT' …
```

Fix dependencies with Maven Enforcer Plug-in

---

.travis.yml
README.md

Hi,
This pull request adds automated continuous integration through [Travis CI](https://docs.travis-ci.com/user/getting-started/). There is a YAML file, _.travis.yml_ that contains the configuration for Travis CI. And in the README.md, we have a new line that adds the image badge.
It is possible to view what the badge will look like on this branch [https://github.com/kinow/cantaloupe/tree/add-travis](https://github.com/kinow/cantaloupe/tree/add-travis). Look at the README, scrolling down a bit the page.
In order to enable it, you - or another person with administrator rights in GitHub for the repository - would have to go to https://travis-ci.org/, log in with GitHub, look for the medusa-project/cantaloupe-project, and enable it.
There are a few settings in Travis CI that you may be …

Add Travis CI to the project

---

pom.xml

Noticed a new warning when running the tests, then tried the `validate` goal to confirm what was wrong.
```
$ mvn validate
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for edu.illinois.library.cantaloupe:Cantaloupe:war:3.4-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: com.fasterxml.jackson.core:jackson-core:jar -> duplicate declaration of version 2.9.0 @ line 361, column 17
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: com.fasterxml.jackson.core:jackson-annotations:jar -> duplicate declaration of version 2.9.0 @ line 366, column 17
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: …
```

Remove unnecessary duplicated dependencies

---

pom.xml
src/test/java/edu/illinois/library/cantaloupe/perf/TIFFImageReaderPerformance.java
src/test/java/edu/illinois/library/cantaloupe/perf/TIFFImageWriterPerformance.java
src/test/java/edu/illinois/library/cantaloupe/perf/package-info.java

This is related to #140. It is not as comprehensive as suggested in the issue. But this pull request contains an example of microbenchmarking with [JMH](http://openjdk.java.net/projects/code-tools/jmh/).
The two benchmark tests included simply extend existing TIFF reader/write tests. Ideally, I think we would like to map a few operations that are considered important and worth keeping an eye every now and then.
Users & developers are then able to run the test in their environment and compare with other results by other users.
This can be useful when choosing hardware for a Cantaloupe server, investigating slowness, and checking for regressions in the code (i.e. run the JMH tests against tag 1.0, and later compare with results from tag 2.0 and see what was the difference).
It is possible …

[WIP] Add performance benchmark tests with JMH

---

src/main/java/edu/illinois/library/cantaloupe/cache/FilesystemCache.java
src/test/java/edu/illinois/library/cantaloupe/cache/FilesystemCacheTest.java

This patch fixes #180. Note that I took the opportunity to re-factor the code a bit as well, rather than just copy the block, since it was a third instance of the cleaner.
FWIW, we ran this today in production with a cache that had over 12 GB in the source cache, a TTL of 3600 seconds and cleaner running every 1800 seconds.

Ensure that the source cache is also purged, and refactor a bit.

---

src/main/java/edu/illinois/library/cantaloupe/processor/OpenJpegProcessor.java

Addressing part of #190, more specifically: Prevents the OpenJpegProcessor from breaking due to the the deletion of the intermediate symlink when attempting to process an unprocessable image by creating separate symlinks for each instance(/request).

Use separate symlinks per instance of OpenJpegProcessor.

---

src/main/java/edu/illinois/library/cantaloupe/resource/AbstractResource.java

Respect any `X-Forwarded-*` headers that are provided. Currently headers
are respected only if `X-Forwarded-Host` header is also provided.
AWS [Elastic Load Balancing](https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/x-forwarded-headers.html), for example, sends `Proto` and `Port` but not `Host`.

Respect X-Forwarded-* headers

---

src/main/java/edu/illinois/library/cantaloupe/cache/FilesystemCache.java

Seems a missing import is breaking the `develop` branch's build.

Add missing java.io.File import

---

pom.xml

I've updated the dependencies as far as I can and still get a clean build from Travis CI.  In particular updating Jetty to the latest version does cause a build failure which is why it's only upgraded to 9.4.20

Update dependencies to addres issue #331

---

src/main/java/edu/illinois/library/cantaloupe/config/Configuration.java
src/main/java/edu/illinois/library/cantaloupe/config/ConfigurationProvider.java
src/main/java/edu/illinois/library/cantaloupe/config/EnvironmentConfiguration.java
src/main/java/edu/illinois/library/cantaloupe/config/HeritablePropertiesConfiguration.java
src/main/java/edu/illinois/library/cantaloupe/config/MapConfiguration.java
src/main/java/edu/illinois/library/cantaloupe/config/PropertiesDocument.java
src/main/java/edu/illinois/library/cantaloupe/util/AWSClientBuilder.java
src/main/java/edu/illinois/library/cantaloupe/util/StringUtils.java
src/test/java/edu/illinois/library/cantaloupe/config/HeritablePropertiesConfigurationTest.java
src/test/java/edu/illinois/library/cantaloupe/util/StringUtilsTest.java
src/test/resources/heritable_level3.properties

Rebased on `4.1` 🔨 
---
Tl;DR: Fixes #333 
There are a few different ways to fix #333 but I feel like this is the root cause. Since Cantaloupe ships an `example.properties` file with keys having no value, it seemed to me that the intended configuration API was broken.
If a key exists in configuration but has no value, it now returns null, whereas before the behaviour depended on the property type (e.g., String would return `""`). This brings the behaviour in line with environment properties, etc. as is standard.

Configuration should return null if key is present but value is empty (rebased on 4.1) #333

---

src/main/java/edu/illinois/library/cantaloupe/processor/codec/jpeg2000/JPEG2000MetadataReader.java

Fully consume the UUID box, even if it is bigger than the buffer size

---

src/main/java/edu/illinois/library/cantaloupe/processor/PdfBoxProcessor.java

Check for null before trying to add a metadata string value to the map.

Check for null value before trying toString - fixes #366

---

src/main/java/edu/illinois/library/cantaloupe/operation/OperationList.java
src/test/java/edu/illinois/library/cantaloupe/operation/OperationListTest.java

Hello, 
A new user here - and very much enjoying Cantaloupe so far. Thank you!
I'm not sure how much you welcome patches, but I've been using the latest 4.1 release and had problems when attempting to control an overlay with a delegate method. The docs indicate that to disable an overlay, the delegate method should return `nil`, however when I tried this, I got a nasty stack trace from within `OperationList` about a null operation.
The fix is to guard against null, but I wasn't sure where in the call stack to fix it, and not being familiar with the code base, I'm not sure what your local styles are. But I noticed two things:
1) that the `OperationList.add()` method already had a non-null check, so I thought adding them to `addAfter` and `addBefore` would be useful. This PR has a commit to …

Bugfix for error when delegate requests nil overlay

---

src/main/java/edu/illinois/library/cantaloupe/processor/codec/jpeg2000/JPEG2000MetadataReader.java

It turns out the issue reported  in #355 is more pervasive than just overly large UUID boxes and some unlucky JPEG2000 files exhibit the same problem when the buffer runs out.

Use readFully instead of read for all JPEG2000MetadataReader operations

---

src/main/java/edu/illinois/library/cantaloupe/processor/codec/jpeg2000/JPEG2000MetadataReader.java

Reverts cantaloupe-project/cantaloupe#361 due to failing tests

Revert "Use readFully instead of read for all JPEG2000MetadataReader operations"

---

cantaloupe.properties.sample
docker/Linux-GraalVM20/Dockerfile
docker/Linux-JDK11/Dockerfile
pom.xml
src/main/java/edu/illinois/library/cantaloupe/config/Key.java
src/main/java/edu/illinois/library/cantaloupe/processor/AutomaticSelectionStrategy.java
src/main/java/edu/illinois/library/cantaloupe/processor/GrokProcessor.java
src/main/java/edu/illinois/library/cantaloupe/processor/ProcessorFactory.java
src/main/resources/admin.vm
src/test/java/edu/illinois/library/cantaloupe/perf/processor/GrokProcessorPerformance.java
src/test/java/edu/illinois/library/cantaloupe/processor/AutomaticSelectionStrategyTest.java
src/test/java/edu/illinois/library/cantaloupe/processor/GrokProcessorTest.java
src/test/java/edu/illinois/library/cantaloupe/resource/admin/AdminResourceUITest.java

Add support for [Grok](https://github.com/GrokImageCompression/grok) decompressor.
Grok features include: 
1. High performance - currently around 1/2 speed of Kakadu demo decoder
1. Fast sub-region decode
1. Supports output to `stdout` for certain file formats
1. Supports `TLM` code stream marker for fast single tile and sub-tile decoding
of large tiled images
1. Supports `PLT` code stream marker for fast sub-tile decoding of large single-tile images
1. Full support for `ICC` profiles and other meta-data such as `XML`, `IPTC` and `XMP`
1. Supports new Part 15 of the standard, aka `High Throughput JPEG 2000`, which promises
up to 10x speed up over current Part 1.

add support for Grok JPEG 2000 decoder
